#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
GRAY='\033[0;37m'
NC='\033[0m'

# build file path
buildPath="./build"

echo -e "${YELLOW}Are you run this Script On 42 lab? (y/n)${NC}"
read answer42

if [ "$answer42" = "y" ]; then
    echo -e "${GREEN}You are on 42 lab${NC}"
    if [ -x "$(command -v docker-compose)" ]; then
        echo -e "${GREEN}good sound, you have docker on your system 😎😁${NC}"
        sleep 1
        # check docker if runing if true kill it
        if [ "$(docker ps)" ]; then
            echo -e "${YELLOW}Docker is running, we will kill it${NC}"
            test -z "$(docker ps -q 2>/dev/null)" && osascript -e 'quit app "Docker"'
            sleep 1
        fi
        # command
    else
      echo -e "${RED}you need install docker on your system from${NC} "
      sleep 2
      echo -e "${YELLOW}Managed Software Center will Open Now${NC}"
      echo -e "${YELLOW}if Docker installed Done plase close Managed Software Center to continue ${NC}"
      # open Managed Software Center
      '/Applications/Managed Software Center.app/Contents/MacOS/Managed Software Center'
    fi
    echo -e "${YELLOW}Do you want to continue? (y/n)${NC}"
    read answer
    if [ "$answer" = "y" ]; then
        echo -e "${GREEN}Good${NC}"
    else
        echo -e "${RED}You are not on 42 lab${NC}"
        exit 1
    fi
    # wait till docker work well
    echo -e "${YELLOW}Wait till docker work well${NC}"
    mkdir -p ~/goinfre/docker
    echo -e "${GRAY}mkdir -p ~/goinfre/docker${NC}"
    sleep 1
    rm -rf ~/Library/Containers/com.docker.docker
    echo -e "${GRAY}rm -rf ~/Library/Containers/com.docker.docker${NC}"
    sleep 1
    ln -s ~/goinfre/docker ~/Library/Containers/com.docker.docker
    echo -e "${GRAY}ln -s ~/goinfre/docker ~/Library/Containers/com.docker.docker${NC}"
    sleep 1
    echo -e "${YELLOW}Do you installed zsh on your device? (y/n)${NC}"
    read answerzsh
    if [ "$answerzsh" = "y" ]; 
      then

        echo -e "${GREEN}add path to ${YELLOW}~/.zshrc${NC}"
        sleep 1
        # check if path is in .zshrc
        if grep -q "42-ValgrindContainer" ~/.zshrc; then
            echo -e "${GREEN}path is in .zshrc${NC}"
        else
            echo -e "${GRAY}add path to .zshrc${NC}"
            echo PATH=\$PATH:$(pwd)  | tee -a ~/.zshrc
            echo -e "${GREEN}path added to .zshrc${NC}"
        fi
      else
        if grep -q "42-ValgrindContainer" ~/.bashrc; then
            echo -e "${GREEN}path is in .bashrc${NC}"
        else
            echo -e "${GRAY}add path to .bashrc${NC}"
            echo PATH=\$PATH:$(pwd)  | tee -a ~/.bashrc
            echo -e "${GREEN}path added to .bashrc${NC}"
        fi
    fi # end if answerzsh
    open -a Docker
    # loop docker ps if true break loop
    while true; do
        docker ps > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo -e "${GREEN}docker is running${NC}"
            break
        else
            echo -e "${RED}Waiting for Docker to run${NC}"
            sleep 1
        fi
    done
else
  echo -e "${RED}Only For 42 lab, and script exit${NC}"
  exit
fi  # end if answer42

if [ ! "$(docker images -a | grep valgrind)" ] ;then
  echo "install for you valgrind 🍽"
  chmod a+rwx "$buildPath"
  /bin/bash $buildPath
  wait
  exit
else 
  echo "good every thing fine 😇"
  exit
fi